source 'https://rubygems.org'

gem 'fluentd', '0.12.14'
gem 'fluent-plugin-forest', '0.3.0'
gem 'fluent-plugin-record-modifier', '0.3.0'
gem 'fluent-plugin-flowcounter', '0.3.0'
gem 'fluent-plugin-rewrite-tag-filter', '1.5.1'
gem 'fluent-plugin-ping-message', '0.1.2'
gem 'fluent-plugin-s3', '0.5.9'
gem 'fluent-plugin-kafka', '0.0.15'
gem 'fluent-plugin-scribe', '0.10.14'
gem 'fluent-plugin-webhdfs', '0.4.1'
gem 'fluent-plugin-elasticsearch', '0.9.0'
gem 'fluent-plugin-newsyslog', :git => 'https://github.com/athenahealth/fluent-plugin-newsyslog.git', :tag => 'v0.1.0'
